/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffRouteRouteImport } from './routes/staff.route'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentDestinationRouteImport } from './routes/student.destination'
import { Route as StudentReasonRouteImport } from './routes/student.reason'
import { Route as StudentStreakRouteImport } from './routes/student.streak'
import { Route as StudentWatchRouteImport } from './routes/student.watch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDestinationRoute = StudentDestinationRouteImport.update({
  id: '/student/destination',
  path: '/student/destination',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentReasonRoute = StudentReasonRouteImport.update({
  id: '/student/reason',
  path: '/student/reason',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentStreakRoute = StudentStreakRouteImport.update({
  id: '/student/streak',
  path: '/student/streak',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentWatchRoute = StudentWatchRouteImport.update({
  id: '/student/watch',
  path: '/student/watch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/staff': typeof StaffRouteRoute
  '/student/destination': typeof StudentDestinationRoute
  '/student/reason': typeof StudentReasonRoute
  '/student/streak': typeof StudentStreakRoute
  '/student/watch': typeof StudentWatchRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/staff': typeof StaffRouteRoute
  '/student/destination': typeof StudentDestinationRoute
  '/student/reason': typeof StudentReasonRoute
  '/student/streak': typeof StudentStreakRoute
  '/student/watch': typeof StudentWatchRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/staff': typeof StaffRouteRoute
  '/student/destination': typeof StudentDestinationRoute
  '/student/reason': typeof StudentReasonRoute
  '/student/streak': typeof StudentStreakRoute
  '/student/watch': typeof StudentWatchRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/staff'
    | '/student/destination'
    | '/student/reason'
    | '/student/streak'
    | '/student/watch'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/staff'
    | '/student/destination'
    | '/student/reason'
    | '/student/streak'
    | '/student/watch'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/staff'
    | '/student/destination'
    | '/student/reason'
    | '/student/streak'
    | '/student/watch'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StaffRouteRoute: typeof StaffRouteRoute
  StudentDestinationRoute: typeof StudentDestinationRoute
  StudentReasonRoute: typeof StudentReasonRoute
  StudentStreakRoute: typeof StudentStreakRoute
  StudentWatchRoute: typeof StudentWatchRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/destination': {
      id: '/student/destination'
      path: '/student/destination'
      fullPath: '/student/destination'
      preLoaderRoute: typeof StudentDestinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/reason': {
      id: '/student/reason'
      path: '/student/reason'
      fullPath: '/student/reason'
      preLoaderRoute: typeof StudentReasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/streak': {
      id: '/student/streak'
      path: '/student/streak'
      fullPath: '/student/streak'
      preLoaderRoute: typeof StudentStreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/watch': {
      id: '/student/watch'
      path: '/student/watch'
      fullPath: '/student/watch'
      preLoaderRoute: typeof StudentWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StaffRouteRoute: StaffRouteRoute,
  StudentDestinationRoute: StudentDestinationRoute,
  StudentReasonRoute: StudentReasonRoute,
  StudentStreakRoute: StudentStreakRoute,
  StudentWatchRoute: StudentWatchRoute,
  StudentIndexRoute: StudentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
